app/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', 'rezerwacja.views.index'),
    url(r'^zapisz_rez/$', 'rezerwacja.views.zapisz_rez'),
]

rezerwacja/models.py
from __future__ import unicode_literals

# -*- coding: utf-8 -*-
from django.db import models



class Stoliki(models.Model):
    nr_stolika = models.IntegerField('Nr Stolika')
    ile_osob = models.IntegerField('Ile Osob')

    class Meta:
        verbose_name = "Stolik"
        verbose_name_plural = "Stoliki"
        
    def __unicode__(self):
        #return self.nr_stolika      
        return unicode(self.nr_stolika) or u''

class Rezerwacje(models.Model):
    data_rezerwacji = models.DateTimeField('Data rezerwacji', auto_now_add=True)
    imie = models.CharField('Imie', max_length=20)
    nazwisko = models.CharField('Nazwisko', max_length=40)
    email = models.EmailField('Email', max_length=254)
    stolik = models.IntegerField('Stolik')
    od = models.DateTimeField('Data od')
    do = models.DateTimeField('Data do')
    ileosob = models.IntegerField('Ilosc osob')

    class Meta:
        verbose_name = "Rezerwacja"
        verbose_name_plural = "Rezerwacje"

    def __unicode__(self):
        return self.imie + " " + self.nazwisko        

rezerwacja/forms.py
from django import forms        
from rezerwacja.models import Rezerwacje

class TestForm(forms.ModelForm):

    class Meta:
        model = Rezerwacje
        fields = ('imie', 'nazwisko', 'email', 'od', 'do', 'stolik', 'ileosob')
        

rezerwacja/views.py
from django.views.decorators.csrf import csrf_protect
from django.shortcuts import render
from django.core.mail import send_mail
from datetime import date
import datetime
from django.db.models import Q
import json
from django.http import HttpResponse

from django.template import RequestContext
from django.shortcuts import render_to_response
from rezerwacja.models import Rezerwacje
from rezerwacja.models import Stoliki
from rezerwacja.email import send_email
from rezerwacja.check import where_empty
from rezerwacja.check import is_busy
from .forms import TestForm


def index(request):
   form = TestForm()
   wolny = 0
   if request.method == "POST":
      form = TestForm(request.POST)
    
      if form.is_valid():
   
	 #walidacja
         stolik = Stoliki.objects.get(nr_stolika=request.POST['stolik'])
         types_list = Rezerwacje.objects.filter(Q(od__gt=datetime.datetime.now()) | Q(do__gt=datetime.datetime.now()))

         zakres='null' 
         rezerwacja_lista = Rezerwacje.objects.filter((Q(od__gt=datetime.datetime.now()) | Q(do__gt=datetime.datetime.now())) & Q(stolik=request.POST['stolik']) )
         if rezerwacja_lista.all().count()>0:
            for item in rezerwacja_lista:
             if u'%s' % (request.POST['od']) <= u'%s' % (item.do) and u'%s' % (request.POST['do']) >=u'%s' % (item.od): 
		od_do=u'%s' % (item.od)+' - '+u'%s' % (item.do)
                zakres='busy'
                break

         
         if int(request.POST['ileosob']) > int(stolik.ile_osob):
             alert = 'Przekroczona ilosc osob dla wybranego stolika, max='+str(stolik.ile_osob)
         elif zakres=='busy':
	      #### busy
	      wolny = where_empty(request.POST)
              alert = 'Stolik nr:'+request.POST['stolik']+' jest zajety w terminie '+od_do
         else:
            alert = 0
        
      return render_to_response('akcept.html',
            {
              'alert':alert,
              'zmienna':request.POST, 
              'cena':int(request.POST['ileosob'])*5,
              'wolny':wolny,
             },
            context_instance=RequestContext(request)
            )
   else:
      return render_to_response('index.html',
            {
              'form':form,
             },
            context_instance=RequestContext(request)
            )
         
def zapisz_rez(request):
    form = request.POST

    post = Rezerwacje(imie=form['imie'], 
                  nazwisko=form['nazwisko'],
                  email=form['email'],
                  od=form['od'],
                  do=form['do'],
                  stolik=form['stolik'],
                  ileosob=form['ileosob'],
    )

    if is_busy(request.POST)=='busy':
       post.save()
       message = 'Zarezerwowano stolik nr:'+request.POST['stolik']+' w terminie '+request.POST['od']+' - '+request.POST['do']
       email = {}		
       email['subject'] = 'Potwierdzenie rezerwacji'
       email['message'] = message
       email['from_email'] = request.POST['email']

       ####################### 
       #   send_email(email)
    
       return HttpResponse(message, content_type="application/json")
    else:
       return HttpResponse("Termin zajety!", status=404)

rezerwacja/templates/akcept.html
{% extends 'base.html' %}

{% block content %}
{% load staticfiles %}
{% load filters %}

   <section class="content">     
   
   {% if alert != 0  %}
          <div class="alert alert-danger alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <h4><i class="icon fa fa-ban"></i>Rezerwacja nie powiodła się.</h4>
                Error : <b>{{ alert|to_date}}</b>

	{% if wolny == 0  %}
 		<div class="bg-aqua-active color-palette"><span>Brak wolnego stolika w wybranym terminie.</span></div>
        {% else %}
		<div class="bg-aqua-active color-palette"><span>W wybranym terminie wolny jest stolik nr: {{ wolny }}</span></div>
        {% endif %}
               
         </div> 
             <div class="box-footer">
                <button type="button" onClick="history.back()" class="btn btn-info pull-right">Powrót do formularza</button>
             </div>
         
   {% else %}

          <div id="sd1" class="alert alert-success alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <h4><i class="icon fa fa-info"></i>Potwierdzenie rezerwacji.</h4>
         </div> 
          <div id="sd2" class="alert alert-success alert-dismissible" style="display:none">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <h4><i class="icon fa fa-check"></i>Rezerwacja wykonana.</h4>
                Potwierdzenie wysłano do: <b>{{ zmienna.email}}</b>
		<div class="bg-red-active color-palette"><span>Z uwagi na ograniczenia serwera i blokowany smtp maile nie są wysyłane!</span></div>
         </div> 
 
           <div class="box box-solid">
            <div class="box-header with-border">
              <i class="fa fa-text-width"></i>

              <h3 class="box-title">Dane Rezerwacji</h3>
            </div>
            <!-- /.box-header -->
	<form method="POST" id="post-form">{% csrf_token %}
            <div class="box-body">
              <dl class="dl-horizontal">
                <dt>Imie</dt>
		<input id="id_imie" name="imie" type="hidden" value="{{ zmienna.imie}}"/>
                <dd>{{ zmienna.imie}}</dd>
                <dt>Nazwisko</dt>
		<input id="id_nazwisko" name="nazwisko" type="hidden" value="{{ zmienna.nazwisko}}"/>
                <dd>{{ zmienna.nazwisko}}</dd>
                <dt>Nr stolika</dt>
		<input id="id_stolik" name="stolik" type="hidden" value="{{ zmienna.stolik}}"/>
                <dd>{{ zmienna.stolik}}</dd>
                <dt>Ilość osób</dt>
		<input id="id_ileosob" name="ileosob" type="hidden" value="{{ zmienna.ileosob}}"/>
                <dd>{{ zmienna.ileosob}}</dd>
                <dt>Data Rezerwacji</dt>
		<input id="id_od" name="od" type="hidden" value="{{ zmienna.od}}"/>
		<input id="id_do" name="do" type="hidden" value="{{ zmienna.do}}"/>
                <dd>{{ zmienna.od}}  -  {{ zmienna.do}}</dd>    
                <dt>Cena</dt>
                <dd>{{ cena}}$</dd> 
		<input id="id_email" name="email" type="hidden" value="{{ zmienna.email}}"/>
              </dl>
            </div>
            <!-- /.box-body -->
	</form>

             <div class="box-footer">
                <button id="save" type="button" class="btn btn-info pull-left">Potwierdz wybor</button>
                <button type="button" onClick="location.href=''" class="btn btn-info pull-right">Powrót do formularza</button>
             </div>
          </div>
          <!-- /.box -->
        </div> 

   {% endif %}
       
   </section>
{% endblock content %}   

{% block script %} 
<script>

$(function () {

	$( "#save" ).click(function() {

            var data = $('#post-form').serializeArray();

	    $.ajax({
		url : "/zapisz_rez/", 
		type : "POST", 
                headers: {'X-CSRFToken': '{{ csrf_token }}'},
                data: data,
                traditional: true,
                dataType: 'text',

		success : function(json) {
                    alert(json); 
                    $("#save").hide();
                    $("#sd1").hide();
                    $("#sd2").show();
 		},

		error : function(xhr,errmsg,err) {
		    alert(xhr.status + ": " + xhr.responseText); 
		}
	    });
	});

});

</script>
{% endblock script %}    

rezerwacja/templates/base.html
{% load staticfiles %}
{% load filters %}

<html>
    <head>
        <title>Django - System rezerwacji stolika</title>

        <!-- Include Required Prerequisites -->
        <script type="text/javascript" src="//cdn.jsdelivr.net/jquery/1/jquery.min.js"></script>
        <script type="text/javascript" src="//cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
        <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/bootstrap/latest/css/bootstrap.css" />
        <!-- Include Date Range Picker -->
        <script type="text/javascript" src="//cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.js"></script>
        <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.css" />
           <!-- Font Awesome -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">     
        <link rel="stylesheet" href="{% static 'css/AdminLTE.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/rezerwacje.css' %}">
        <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    </head>
    <body>

      <div class="callout callout-info">
        <h4>System rezerwacji stolika</h4>
      </div>

    <section class="content-header">

      <div class="box box-default">
        <div class="box-header with-border ">
          <h3 class="box-title">Założenia</h3>

          <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
            <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-remove"></i></button>
          </div>
        </div>
            <ol>
                <li>Wybranie z kalendarza daty i godziny rezerwacji</li>
                <li>Podanie imienia i nazwiska rezerwującego</li>
                <li>Podanie adresu email</li>
                <li>Wybranie stolika (stoliki powinny być pokazane w sposób graficzny w przykładowej Sali)</li>
                <li>Określenie liczby osób</li>
                <li>System powinien poinformować jeżeli stolik jest wolny, jeżeli zajęty wyświetlić informacje o
                    terminie zajętości i zaproponować stolik wolny w tym terminie z uwzględnieniem ilości osób
                    które mogą się zmieścić przy danym stoliku.</li>
                <li>System powinien wyświetlić podsumowanie do potwierdzenia przez użytkownika wraz z ceną
                    rezerwacji 5$ za osobę.</li>
                <li>Po potwierdzeniu rezerwacji informacja powinna się wysłać na e-mail.</li>
              </ol>
      </div>

   </section>

{% block content %}{% endblock content %}
{% block modal %}{% endblock modal %} 
{% block script %}{% endblock script %}   
    
    </body>
</html>

rezerwacja/templates/content_form.html
{% load staticfiles %}
{% load filters %} 

   <section class="content">      
      
    <form method="POST" id="form_zad" class="post-form">{% csrf_token %}

          <div class="box box-primary">
            <div class="box-header">
              <h3 class="box-title">Rezerwacja stolika </h3>
            </div>
            <div class="box-body">
            
              <div class="form-group">
                <label>Początek rezerwacji:</label>
                <div class="input-group">
                  <div class="input-group-addon">
                    <i class="fa fa-clock-o"></i>
                  </div>
                  {{ form.od|add_css_attr:'form-control,true'   }}
                </div>
              </div>

              <div class="form-group">
                <label>Koniec rezerwacji:</label>
                <div class="input-group">
                  <div class="input-group-addon">
                    <i class="fa fa-clock-o"></i>
                  </div>
                  {{ form.do|add_css_attr:'form-control,true'   }}
                </div>
              </div>      
              
             <div class="form-group">
                <label>Imie:</label>
                <div class="input-group">
                  <div class="input-group-addon">
                    <i class="fa fa-circle-thin"></i>
                  </div>                
                  {{ form.imie|add_css_attr:'form-control,true'  }}
                </div>
              </div> 

              <div class="form-group">
                <label>Nazwisko:</label>
                <div class="input-group">
                  <div class="input-group-addon">
                    <i class="fa fa-circle-thin"></i>
                  </div>                
                  {{ form.nazwisko|add_css_attr:'form-control,true'}}
                </div>
              </div> 

              <div class="form-group">
                <label>Email:</label>
                <div class="input-group">
                  <div class="input-group-addon">
                    <i class="fa fa-envelope"></i>
                  </div>
                  {{ form.email|add_css_attr:'form-control,true' }}
                </div>
              </div> 

              <div class="form-group">
                <label>Nr stolika:</label>
                <div class="input-group" data-toggle="modal" data-target="#myModal">
                   <div class="input-group-addon">
                    <i class="fa fa-coffee" data-toggle="modal" data-target="#myModal"></i>
                  </div>
                  {{ form.stolik|add_css_attr:'form-control,true'  }}
                </div>
              </div> 
              
              <div class="form-group">
                <label>ilość osób:</label>
                <div class="input-group">
                  <div class="input-group-addon">
                    <i class="fa fa-circle-thin"></i>
                  </div>                
                  {{ form.ileosob|add_css_attr:'form-control,true'  }}
                </div>
              </div>     
                        
              <div class="box-footer">
                <button type="submit" class="btn btn-info ">Zapisz rezerwacje</button>
              </div>
              <!-- /.box-footer -->
            </form>             
            </div>
   </section>

rezerwacja/templates/index.html
{% extends 'base.html' %}

{% block content %}
 {% include 'content_form.html' %}
{% endblock content %}

{% block modal %}
 {% include 'modal.html' %}
{% endblock modal %} 

{% block script %}
 {% include 'script.html' %}
{% endblock script %}   

rezerwacja/templates/modal.html
{% load staticfiles %}
{% load filters %}

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Wybór stolika</h4>
      </div>
      <div class="modal-body">
      
<table width="500" border="0" cellpadding="0" cellspacing="0" summary="Split Image">
<tr>
 <td title="Nr 1"><a href="#nr-1" id="1" ><img src="{% static 'img/plan/plan23_part1x1.jpg' %}" width="166" height="133" alt="Part 1x1" border="0" onmouseover="this.src='{% static 'img/plan/plan23_swap_part1x1.jpg' %}';return true;" onmouseout="this.src='{% static 'img/plan/plan23_part1x1.jpg' %}';return true;" /></a></td>
 <td><img src="{% static 'img/plan/plan23_swap_part1x2.jpg' %}" width="166" height="133" alt="Part 1x2" border="0" /></td>
 <td title="Nr 2"><a href="#nr-2" id="2" ><img src="{% static 'img/plan/plan23_part1x3.jpg' %}" width="168" height="133" alt="Part 1x3" border="0" onmouseover="this.src='{% static 'img/plan/plan23_swap_part1x3.jpg' %}';return true;" onmouseout="this.src='{% static 'img/plan/plan23_part1x3.jpg' %}';return true;" /></a></td>
</tr>
<tr>
 <td title="Nr 3"><a href="#nr-3" id="3" ><img src="{% static 'img/plan/plan23_part2x1.jpg' %}" width="166" height="133" alt="Part 2x1" border="0" onmouseover="this.src='{% static 'img/plan/plan23_swap_part2x1.jpg' %}';return true;" onmouseout="this.src='{% static 'img/plan/plan23_part2x1.jpg' %}';return true;" /></a></td>
 <td title="Nr 4"><a href="#nr-4" id="4" ><img src="{% static 'img/plan/plan23_part2x2.jpg' %}" width="166" height="133" alt="Part 2x2" border="0" onmouseover="this.src='{% static 'img/plan/plan23_swap_part2x2.jpg' %}';return true;" onmouseout="this.src='{% static 'img/plan/plan23_part2x2.jpg' %}';return true;" /></a></td>
 <td title="Nr 5"><a href="#nr-5" id="5" ><img src="{% static 'img/plan/plan23_part2x3.jpg' %}" width="168" height="133" alt="Part 2x3" border="0" onmouseover="this.src='{% static 'img/plan/plan23_swap_part2x3.jpg' %}';return true;" onmouseout="this.src='{% static 'img/plan/plan23_part2x3.jpg' %}';return true;" /></a></td>
</tr>
<tr>
 <td title="Nr 6"><a href="#nr-6" id="6" ><img src="{% static 'img/plan/plan23_part3x1.jpg' %}" width="166" height="133" alt="Part 3x1" border="0" onmouseover="this.src='{% static 'img/plan/plan23_swap_part3x1.jpg' %}';return true;" onmouseout="this.src='{% static 'img/plan/plan23_part3x1.jpg' %}';return true;" /></a></td>
 <td title="Nr 7"><a href="#nr-7" id="7" ><img src="{% static 'img/plan/plan23_part3x2.jpg' %}" width="166" height="133" alt="Part 3x2" border="0" onmouseover="this.src='{% static 'img/plan/plan23_swap_part3x2.jpg' %}';return true;" onmouseout="this.src='{% static 'img/plan/plan23_part3x2.jpg' %}';return true;" /></a></td>
 <td title="Nr 8"><a href="#nr-8" id="8" ><img src="{% static 'img/plan/plan23_part3x3.jpg' %}" width="168" height="133" alt="Part 3x3" border="0" onmouseover="this.src='{% static 'img/plan/plan23_swap_part3x3.jpg' %}';return true;" onmouseout="this.src='{% static 'img/plan/plan23_part3x3.jpg' %}';return true;" /></a></td>
</tr>
<tr>
 <td title="Nr 9"><a href="#nr-9" id="9" ><img src="{% static 'img/plan/plan23_part4x1.jpg' %}" width="166" height="135" alt="Part 4x1" border="0" onmouseover="this.src='{% static 'img/plan/plan23_swap_part4x1.jpg' %}';return true;" onmouseout="this.src='{% static 'img/plan/plan23_part4x1.jpg' %}';return true;" /></a></td>
 <td title="Nr 10"><a href="#nr-10" id="10" ><img src="{% static 'img/plan/plan23_part4x2.jpg' %}" width="166" height="135" alt="Part 4x2" border="0" onmouseover="this.src='{% static 'img/plan/plan23_swap_part4x2.jpg' %}';return true;" onmouseout="this.src='{% static 'img/plan/plan23_part4x2.jpg' %}';return true;" /></a></td>
 <td title="Nr 11"><a href="#nr-11" id="11" ><img src="{% static 'img/plan/plan23_part4x3.jpg' %}" width="168" height="135" alt="Part 4x3" border="0" onmouseover="this.src='{% static 'img/plan/plan23_swap_part4x3.jpg' %}';return true;" onmouseout="this.src='{% static 'img/plan/plan23_part4x3.jpg' %}';return true;" /></a></td>
</tr>
</table>    

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

rezerwacja/templates/script.html
{% load staticfiles %}
{% load filters %}

<script>

  $(function () {

    $('#id_od').daterangepicker({
          startDate: moment(),
          endDate: moment().subtract('hours', 12),
    "singleDatePicker": true,
    "timePicker": true,
    "timePicker24Hour": true,
    "timePickerIncrement": 30,
    "opens": "left",
    "drops": "up",
        locale: {
        format: 'YYYY-MM-DD HH:mm'
        }
      });
      
    $('#id_do').daterangepicker({
          startDate: moment(),
          endDate: moment(),      
    "singleDatePicker": true,
    "timePicker": true,
    "timePicker24Hour": true,
    "timePickerIncrement": 30,
    "opens": "left",
    "drops": "up",
        locale: {
        format: 'YYYY-MM-DD HH:mm'
        }
      });   

$('#id_od').val('');
$('#id_do').val(''); 

$( "a" ).click(function() {
  var nr = $(this).attr("id");
   $('#id_stolik').val(nr);
   $('#myModal').modal('hide');
});
     

$( "#id_stolik" ).change(function () {
  var max = 11;
  if ($("#id_stolik").val()<1 && $("#id_stolik").val()!=''){
	alert('Nr stolika musi być wartością większą od zera!');
	$("#id_stolik").val('');
   };
  if ($("#id_stolik").val()>max ){
	alert('Niewlaściwy nr stolika!');
	$("#id_stolik").val('');
   };
 }).change();

$( "#id_ileosob" ).change(function () {
  var max = 20;
  if ($("#id_ileosob").val()<0 ){
	alert('Ilość osób nie może być wartością ujemną!');
	$("#id_ileosob").val('');
   };
  if ($("#id_ileosob").val()>max ){
	alert('Brak stolika na wskazaną liczbę osób! \n:max 10 osób');
	$("#id_ileosob").val('');
   };
 }).change();


$("#form_zad").on('submit',function(){
   var d = new Date();
   var hour = d.getHours()<10?'0'+d.getHours():''+d.getHours();
   var minute = d.getMinutes()<10?'0'+d.getMinutes():''+d.getMinutes();
   var mont1 = d.getMonth() + 1;
   var month = mont1<10?'0'+mont1:''+mont1;
   var day = d.getDate()<10?'0'+d.getDate():''+d.d.getDate();
   var now = d.getFullYear() + "-" + month + "-" + day + " " + hour + ":" + minute;
   var dat_od = $("#id_od").val();


 if(($("#id_od").val()>=$("#id_do").val()) && $("#id_do").val().length !=''){
  alert('Nieprawidłowy zakres dat! \n"Koniec rezerwacji" musi być starszy od "Początek rezerwacji"');
  return false;
 } else if (dat_od<now && $("#id_od").val().length !=''){
  alert('Nieprawidłowa data [Początek rezerwacji] '+ now);
  return false;
 }
});

  });

</script>

rezerwacja/templates/zapis.html
{% extends 'base.html' %}

{% block content %}
{% load staticfiles %}
{% load filters %}

   <section class="content">     
   
   {% if alert != 0  %}
          <div class="alert alert-danger alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <h4><i class="icon fa fa-ban"></i>Rezerwacja nie powiodła się.</h4>
                Error : <b>{{ alert|to_date}}</b>

	{% if wolny == 0  %}
 		<div class="bg-aqua-active color-palette"><span>Brak wolnego stolika w wybranym terminie.</span></div>
        {% else %}
		<div class="bg-aqua-active color-palette"><span>W wybranym terminie wolny jest stolik nr: {{ wolny }}</span></div>
        {% endif %}
               
         </div> 
             <div class="box-footer">
                <button type="button" onClick="history.back()" class="btn btn-info pull-right">Powrót do formularza</button>
             </div>
         
   {% else %}

          <div class="alert alert-success alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <h4><i class="icon fa fa-check"></i>Rezerwacja wykonana.</h4>
                Potwierdzenie wysłano do: <b>{{ zmienna.email}}</b>
		<div class="bg-red-active color-palette"><span>Z uwagi na ograniczenia serwera i blokowany smtp maile nie są wysyłane!</span></div>
         </div> 
 
           <div class="box box-solid">
            <div class="box-header with-border">
              <i class="fa fa-text-width"></i>

              <h3 class="box-title">Dane Rezerwacji</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <dl class="dl-horizontal">
                <dt>Imie</dt>
                <dd>{{ zmienna.imie}}</dd>
                <dt>Nazwisko</dt>
                <dd>{{ zmienna.nazwisko}}</dd>
                <dt>Nr stolika</dt>
                <dd>{{ zmienna.stolik}}</dd>
                <dt>Ilość osób</dt>
                <dd>{{ zmienna.ileosob}}</dd>
                <dt>Data Rezerwacji</dt>
                <dd>{{ zmienna.od}}  -  {{ zmienna.do}}</dd>    
                <dt>Cena</dt>
                <dd>{{ cena}}$</dd>            
              </dl>
            </div>
            <!-- /.box-body -->
             <div class="box-footer">
                <button type="button" onClick="location.href=''" class="btn btn-info pull-right">Powrót do formularza</button>
             </div>
          </div>
          <!-- /.box -->
        </div> 

   {% endif %}
       
   </section>
{% endblock content %}   

{% block script %} 
<script>

  $(function () {


  });

</script>
{% endblock script %}    